server:
  port: 8030
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/ibrxhxm/learn-microservices-demo-config-server
#          username: ibrxhxm
#          password: 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
#          clone-on-start: true
#          skipSslValidation: true
#          default-label: main
        native:
          search-locations: file://${user.home}/IdeaProjects/learn-microservices-demo-config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: password

  bus:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: busrefresh