server:
  port: 8020

spring:
  application:
    name: api-gateway
  devtools:
    restart:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8030
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: userws
          uri: lb://userws
          predicates:
            - Path=/userws/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/userws/(?<segment>.*), /$\{segment}

        - id: user-ws-login
          uri: lb://userws
          predicates:
            - Path=/userws/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/userws/(?<segment>.*), /$\{segment}

        - id: user-ws-get-put-delete
          uri: lb://userws
          predicates:
            - Path=/userws/users/**
            - Method=GET, PUT, DELETE
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/userws/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter

        - id: user-ws-actuator
          uri: lb://userws/actuator/mappings
          predicates:
            - Path=/userws/actuator/mappings
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: password

  bus:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    hostname: 192.168.88.32

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - gateway
          - beans
          - health
          - httptrace
          - info

#security:
#  config:
#    token_lifespan: 864000000
#    token_secret: notSoSecretToken